namespace Unity.ExcelXML.Tests {
  public static class SampleData {
    private static string xmlns_ss = "xmlns:ss=\"urn:schemas-microsoft-com:office:spreadsheet\"";
    public static string RowXml0 = $"<ss:Row {xmlns_ss} ss:AutoFitHeight=\"0\" ss:StyleID=\"s66\"><ss:Cell ss:StyleID=\"s67\"/><ss:Cell ss:StyleID=\"s68\"/><ss:Cell ss:StyleID=\"s68\"/><ss:Cell ss:StyleID=\"s68\"/><ss:Cell ss:StyleID=\"s68\"/><ss:Cell ss:MergeAcross=\"1\" ss:StyleID=\"m472611632\"><ss:Data ss:Type=\"String\">Event Type</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s68\"/><ss:Cell ss:StyleID=\"s68\"/><ss:Cell ss:MergeAcross=\"11\" ss:StyleID=\"m472611652\"><ss:Data ss:Type=\"String\">Run Months</ss:Data></ss:Cell><ss:Cell ss:MergeAcross=\"6\" ss:StyleID=\"m472611672\"><ss:Data ss:Type=\"String\">Run Days</ss:Data></ss:Cell><ss:Cell ss:MergeAcross=\"2\" ss:StyleID=\"m472611692\"><ss:Data ss:Type=\"String\">Run Modes</ss:Data></ss:Cell></ss:Row>";
    public static string RowXml1 = $"<ss:Row {xmlns_ss} ss:AutoFitHeight=\"0\" ss:Height=\"15.75\" ss:StyleID=\"s66\"><ss:Cell ss:StyleID=\"s67\"><ss:Data ss:Type=\"String\">Name</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s68\"><ss:Data ss:Type=\"String\">EventID</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s68\"><ss:Data ss:Type=\"String\">ModuleID</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s68\"><ss:Data ss:Type=\"String\">Event Data</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s68\"><ss:Data ss:Type=\"String\">Active</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s83\"><ss:Data ss:Type=\"String\">Override</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s84\"><ss:Data ss:Type=\"String\">Run Once</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s68\"><ss:Data ss:Type=\"String\">Time Format</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s68\"><ss:Data ss:Type=\"String\">Start Time</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s83\"><ss:Data ss:Type=\"String\">Jan</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s85\"><ss:Data ss:Type=\"String\">Feb</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s85\"><ss:Data ss:Type=\"String\">Mar</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s85\"><ss:Data ss:Type=\"String\">Apr</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s85\"><ss:Data ss:Type=\"String\">May</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s85\"><ss:Data ss:Type=\"String\">June</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s85\"><ss:Data ss:Type=\"String\">Jul</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s85\"><ss:Data ss:Type=\"String\">Aug</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s85\"><ss:Data ss:Type=\"String\">Sept</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s85\"><ss:Data ss:Type=\"String\">Oct</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s85\"><ss:Data ss:Type=\"String\">Nov</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s84\"><ss:Data ss:Type=\"String\">Dec</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s83\"><ss:Data ss:Type=\"String\">Sun</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s85\"><ss:Data ss:Type=\"String\">Mon</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s85\"><ss:Data ss:Type=\"String\">Tue</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s85\"><ss:Data ss:Type=\"String\">Wed</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s86\"><ss:Data ss:Type=\"String\">Thu</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s86\"><ss:Data ss:Type=\"String\">Fri</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s87\"><ss:Data ss:Type=\"String\">Sat</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s88\"><ss:Data ss:Type=\"String\">In</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s86\"><ss:Data ss:Type=\"String\">Out</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s87\"><ss:Data ss:Type=\"String\">Vac</ss:Data></ss:Cell></ss:Row>";
    public static string RowXml2 = $"<ss:Row {xmlns_ss} ss:AutoFitHeight=\"0\"><ss:Cell><ss:Data ss:Type=\"String\">Test Event 3</ss:Data></ss:Cell><ss:Cell><ss:Data ss:Type=\"Number\">3</ss:Data></ss:Cell><ss:Cell><ss:Data ss:Type=\"Number\">1</ss:Data></ss:Cell><ss:Cell ss:Index=\"5\"><ss:Data ss:Type=\"Number\">1</ss:Data></ss:Cell><ss:Cell><ss:Data ss:Type=\"Number\">0</ss:Data></ss:Cell><ss:Cell><ss:Data ss:Type=\"Number\">0</ss:Data></ss:Cell><ss:Cell><ss:Data ss:Type=\"String\">05 Date Time</ss:Data></ss:Cell><ss:Cell ss:StyleID=\"s91\"><ss:Data ss:Type=\"DateTime\">2015-04-01T21:30:00.000</ss:Data></ss:Cell></ss:Row>";
    public static string TableXml = $"<Table {xmlns_ss} ss:ExpandedColumnCount=\"31\">{RowXml0}{RowXml1}{RowXml2}</Table>";
  }
}
